//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cliente()
        {
            this.estadia = new HashSet<estadia>();
            this.factura = new HashSet<factura>();
        }
    
        public int id_cliente { get; set; }
        public Nullable<bool> cliente_estado { get; set; }
        public string cliente_nombre { get; set; }
        public string cliente_apellido { get; set; }
        public string cliente_email { get; set; }
        public Nullable<bool> cliente_email_invalido { get; set; }
        public Nullable<System.DateTime> cliente_fecha_nacimiento { get; set; }
        public Nullable<int> id_tipo_documento { get; set; }
        public string cliente_numero_documento { get; set; }
        public string cliente_telefono { get; set; }
        public Nullable<int> Id_direccion { get; set; }
        public Nullable<int> Id_pais { get; set; }
    
        public virtual direccion direccion { get; set; }
        public virtual pais pais { get; set; }
        public virtual tipo_documento tipo_documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estadia> estadia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura> factura { get; set; }
    }
}
