//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumible_por_estadia
    {
        public int id_consumible_por_estadia { get; set; }
        public Nullable<int> id_consumible { get; set; }
        public Nullable<int> id_estadia { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual consumible consumible { get; set; }
        public virtual estadia estadia { get; set; }
    }
}
