//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class estadia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public estadia()
        {
            this.consumible_por_estadia = new HashSet<consumible_por_estadia>();
            this.factura = new HashSet<factura>();
        }
    
        public int id_estadia { get; set; }
        public Nullable<System.DateTime> estadia_fecha_inicio { get; set; }
        public Nullable<int> estadia_cantidad_noches { get; set; }
        public Nullable<int> id_habitacion { get; set; }
        public Nullable<int> id_reserva { get; set; }
        public Nullable<int> id_cliente { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consumible_por_estadia> consumible_por_estadia { get; set; }
        public virtual habitacion habitacion { get; set; }
        public virtual reserva reserva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura> factura { get; set; }
    }
}
