//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public factura()
        {
            this.item_factura = new HashSet<item_factura>();
        }
    
        public int id_factura { get; set; }
        public Nullable<int> factura_numero { get; set; }
        public string factura_tipo { get; set; }
        public Nullable<System.DateTime> factura_fecha { get; set; }
        public Nullable<double> factura_total { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_estadia { get; set; }
        public Nullable<int> id_hotel { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual estadia estadia { get; set; }
        public virtual hotel hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item_factura> item_factura { get; set; }
    }
}
