//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_factura
    {
        public int id_item_factura { get; set; }
        public Nullable<int> item_factura_cantidad { get; set; }
        public Nullable<double> item_factura_monto { get; set; }
        public Nullable<int> id_factura { get; set; }
        public Nullable<int> id_consumible { get; set; }
    
        public virtual consumible consumible { get; set; }
        public virtual factura factura { get; set; }
    }
}
