//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class metodo_de_pago
    {
        public int id_metodo_de_pago { get; set; }
        public string metodo_de_pago_nombre { get; set; }
        public string metodo_de_pago_detalles { get; set; }
    }
}
