//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class regimen_por_hotel
    {
        public int id_regimen_por_hotel { get; set; }
        public Nullable<int> id_regimen { get; set; }
        public Nullable<int> id_hotel { get; set; }
    
        public virtual hotel hotel { get; set; }
        public virtual regimen regimen { get; set; }
    }
}
