//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reserva()
        {
            this.estadia = new HashSet<estadia>();
        }
    
        public int id_reserva { get; set; }
        public Nullable<System.DateTime> reserva_fecha_inicio { get; set; }
        public Nullable<int> reserva_cantidad_noches { get; set; }
        public Nullable<int> reserva_numero_codigo { get; set; }
        public Nullable<int> Id_reserva_cambiada_por_user { get; set; }
        public Nullable<int> Id_hotel { get; set; }
        public Nullable<int> Id_habitacion { get; set; }
        public Nullable<int> Id_reserva_estado { get; set; }
        public Nullable<int> Id_regimen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estadia> estadia { get; set; }
        public virtual estado_reserva estado_reserva { get; set; }
        public virtual habitacion habitacion { get; set; }
        public virtual hotel hotel { get; set; }
        public virtual regimen regimen { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
