//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.reserva = new HashSet<reserva>();
        }
    
        public int id_usuario { get; set; }
        public string usuario_username { get; set; }
        public string usuario_nombre { get; set; }
        public string usuario_apellido { get; set; }
        public string usuario_password { get; set; }
        public string usuario_email { get; set; }
        public Nullable<System.DateTime> usuario_fecha_nacimiento { get; set; }
        public Nullable<int> id_tipo_documento { get; set; }
        public string usuario_numero_documento { get; set; }
        public string usuario_telefono { get; set; }
        public Nullable<bool> usuario_habilitado { get; set; }
        public Nullable<int> Id_rol { get; set; }
        public Nullable<int> Id_hotel { get; set; }
    
        public virtual hotel hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reserva> reserva { get; set; }
        public virtual rol rol { get; set; }
        public virtual tipo_documento tipo_documento { get; set; }
    }
}
